"""Feature engineering: raw synthetic daily activity -> ML-ready samples.

⚠  IMPORTANT — the input dataset and every feature derived here are SYNTHETIC.
   - They are generated by ``generator.py`` (``data_source="synthetic"``) and
     are NOT real FitQuest user data.
   - This pipeline demonstrates *feasibility of the ML data path only*. It
     does NOT establish any real-world predictive performance.
   - Real FitQuest telemetry will eventually replace/augment the synthetic
     dataset; the schema here is designed so real rows can flow through the
     same code under a different ``data_source`` label.

Semantics (leakage policy):
    Every feature describes one user *as of the end of day D* and is computed
    ONLY from that user's days D and earlier. No future row (D+1, D+2, ...)
    ever contributes to a feature value for day D, and users never share
    history. Rolling windows are *trailing and inclusive of today*, and they
    EXPAND at the start of a user's history (a 7-day average on the user's
    very first day is just that day's value) so no early rows are dropped.

No ML target is defined here. Phase 4B.3 will decide the learning target;
deliberately *not* labeling rows with the rules engine's recommendation
outcomes, which would mostly teach a model to replay the existing rules.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import generator
from generator import DATA_SOURCE, STREAK_MIN_STEPS

TOOL_DIR = Path(__file__).resolve().parent
DEFAULT_INPUT = TOOL_DIR / "output" / "synthetic_fitness_dataset.csv"
DEFAULT_OUTPUT = TOOL_DIR / "output" / "synthetic_fitness_features.csv"
DEFAULT_MANIFEST = TOOL_DIR / "output" / "synthetic_fitness_features_manifest.json"

# Columns kept for traceability/ordering only — NEVER model features.
METADATA_COLUMNS = ["synthetic_user_id", "day"]
EXCLUDED_METADATA = ["synthetic_user_id", "day", "data_source"]

# The model feature matrix, in canonical order (21 features).
MODEL_FEATURES = [
    # activity
    "steps_today",
    "active_minutes_today",
    "steps_3d_avg",
    "steps_7d_avg",
    "active_minutes_3d_avg",
    "active_minutes_7d_avg",
    "activity_days_7d",
    "steps_change_vs_7d_avg",
    # consistency
    "current_streak",
    "goal_completion_rate_7d",
    "days_since_active",
    # territory
    "hexes_owned",
    "captures_7d",
    "losses_7d",
    "territory_change_7d",
    "defense_steps_7d",
    "defense_ratio_7d",
    # goals
    "goal_steps",
    "goal_completed_today",
    # small set of justified derived extras
    "active_today",
    "goal_progress_ratio",
]

OUTPUT_COLUMNS = METADATA_COLUMNS + MODEL_FEATURES + ["data_source"]

# Raw integer fields (the generator emits ints; CSV rereads give strings).
_INT_FIELDS = (
    "steps",
    "active_minutes",
    "hexes_owned",
    "hexes_captured",
    "hexes_lost",
    "defense_steps",
    "streak",
    "goal_steps",
    "goal_completed",
)

# Machine-readable manifest: one entry per output column. Metadata entries
# carry ``allowed_for_training: false`` so the exclusion is explicit, not
# implicit. ``window`` documents the exact rows that feed each feature
# ("D" = the sample's own day; "D-k..D" = trailing inclusive window).
FEATURE_MANIFEST = [
    # ── metadata (never features) ──────────────────────────────────────────
    {
        "feature_name": "synthetic_user_id",
        "description": "Traceability identifier only; not a predictive feature.",
        "source_fields": ["synthetic_user_id"],
        "window": "n/a",
        "allowed_for_training": False,
    },
    {
        "feature_name": "day",
        "description": "ISO date kept for ordering/traceability; not a predictive feature.",
        "source_fields": ["day"],
        "window": "n/a",
        "allowed_for_training": False,
    },
    # ── activity ───────────────────────────────────────────────────────────
    {
        "feature_name": "steps_today",
        "description": "Steps recorded on day D.",
        "source_fields": ["steps"],
        "window": "current day (D)",
        "allowed_for_training": True,
    },
    {
        "feature_name": "active_minutes_today",
        "description": "Active-bout minutes recorded on day D.",
        "source_fields": ["active_minutes"],
        "window": "current day (D)",
        "allowed_for_training": True,
    },
    {
        "feature_name": "steps_3d_avg",
        "description": "Mean steps over days D-2..D (expanding at history start).",
        "source_fields": ["steps"],
        "window": "trailing 3 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "steps_7d_avg",
        "description": (
            "Mean steps over days D-6..D; e.g. on 2025-01-07 it is the mean of "
            "2025-01-01..2025-01-07. Expands at history start."
        ),
        "source_fields": ["steps"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "active_minutes_3d_avg",
        "description": "Mean active minutes over days D-2..D (expanding).",
        "source_fields": ["active_minutes"],
        "window": "trailing 3 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "active_minutes_7d_avg",
        "description": "Mean active minutes over days D-6..D (expanding).",
        "source_fields": ["active_minutes"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "activity_days_7d",
        "description": (
            "Count of days with steps >= 1000 (the activity bar) in days D-6..D."
        ),
        "source_fields": ["steps"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "steps_change_vs_7d_avg",
        "description": (
            "steps_today minus the mean steps of the PREVIOUS 7 days (D-7..D-1, "
            "expanding at history start). 0.0 on the user's first day (no "
            "baseline yet). Prior-day baseline, so it is never self-referential."
        ),
        "source_fields": ["steps"],
        "window": "prior 7 days excl. D (D-7..D-1)",
        "allowed_for_training": True,
    },
    # ── consistency ────────────────────────────────────────────────────────
    {
        "feature_name": "current_streak",
        "description": (
            "Consecutive days ending on D with steps >= 1000 (the raw streak)."
        ),
        "source_fields": ["streak"],
        "window": "current day (D), cumulative history",
        "allowed_for_training": True,
    },
    {
        "feature_name": "goal_completion_rate_7d",
        "description": "Fraction of days D-6..D where the daily goal was met.",
        "source_fields": ["goal_completed"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "days_since_active",
        "description": (
            "Days since the most recent day with steps >= 1000: 0 if D itself "
            "is active; otherwise D minus that day's index. If no active day "
            "exists in the available history, it is the number of days elapsed "
            "since the day before the history began (index + 1)."
        ),
        "source_fields": ["steps"],
        "window": "current day + lookback through history",
        "allowed_for_training": True,
    },
    # ── territory ──────────────────────────────────────────────────────────
    {
        "feature_name": "hexes_owned",
        "description": "Hexes owned at the END of day D (the raw ledger value).",
        "source_fields": ["hexes_owned"],
        "window": "current day (D), end-of-day state",
        "allowed_for_training": True,
    },
    {
        "feature_name": "captures_7d",
        "description": "Hexes captured over days D-6..D.",
        "source_fields": ["hexes_captured"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "losses_7d",
        "description": "Hexes lost over days D-6..D.",
        "source_fields": ["hexes_lost"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "territory_change_7d",
        "description": (
            "hexes_owned[D] minus hexes_owned[D-7] (net change over the last "
            "7 days). Before day 8 of a history the baseline is 0 (holdings at "
            "history start)."
        ),
        "source_fields": ["hexes_owned"],
        "window": "D vs D-7",
        "allowed_for_training": True,
    },
    {
        "feature_name": "defense_steps_7d",
        "description": "Defense/reinforcement steps over days D-6..D.",
        "source_fields": ["defense_steps"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    {
        "feature_name": "defense_ratio_7d",
        "description": (
            "defense_steps_7d divided by total steps over the same window "
            "(D-6..D); 0.0 when the window's steps sum to 0."
        ),
        "source_fields": ["defense_steps", "steps"],
        "window": "trailing 7 days incl. D",
        "allowed_for_training": True,
    },
    # ── goals ──────────────────────────────────────────────────────────────
    {
        "feature_name": "goal_steps",
        "description": "The user's fixed daily step goal (constant per user).",
        "source_fields": ["goal_steps"],
        "window": "n/a (per-user constant)",
        "allowed_for_training": True,
    },
    {
        "feature_name": "goal_completed_today",
        "description": "1 iff steps_today >= goal_steps (derived in the raw data).",
        "source_fields": ["goal_completed"],
        "window": "current day (D)",
        "allowed_for_training": True,
    },
    # ── justified derived extras ───────────────────────────────────────────
    {
        "feature_name": "active_today",
        "description": (
            "1 iff steps_today >= 1000 — the binary activity signal the game's "
            "streak/capture logic keys on; cheap and directly useful."
        ),
        "source_fields": ["steps"],
        "window": "current day (D)",
        "allowed_for_training": True,
    },
    {
        "feature_name": "goal_progress_ratio",
        "description": (
            "steps_today / goal_steps — scale-free goal progress (can exceed "
            "1.0); 0.0 if the goal is 0 (never occurs in the synthetic data)."
        ),
        "source_fields": ["steps", "goal_steps"],
        "window": "current day (D)",
        "allowed_for_training": True,
    },
    {
        "feature_name": "data_source",
        "description": (
            "Provenance label, always 'synthetic' here; never a feature."
        ),
        "source_fields": ["data_source"],
        "window": "n/a",
        "allowed_for_training": False,
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# Normalization & helpers
# ─────────────────────────────────────────────────────────────────────────────


def _normalize_row(raw: dict) -> dict:
    """Coerce one raw row (dict of ints or CSV strings) into typed values."""
    missing = [c for c in generator.COLUMNS if c not in raw]
    if missing:
        raise ValueError(f"raw row is missing columns: {missing}")
    row = dict(raw)
    for field in _INT_FIELDS:
        row[field] = int(row[field])
    return row


def _window(values: list, i: int, size: int) -> list:
    """Trailing inclusive window: values[max(0, i-size+1) .. i]."""
    return values[max(0, i - size + 1) : i + 1]


def _mean(values: list) -> float:
    return sum(values) / len(values)


def _f6(value: float) -> float:
    """Round floats to 6 decimals for tidy, deterministic CSV output."""
    return round(float(value), 6)


def _days_since_active(steps: list[int], i: int) -> int:
    """Days elapsed since the most recent active day (see manifest)."""
    if steps[i] >= STREAK_MIN_STEPS:
        return 0
    j = i - 1
    while j >= 0 and steps[j] < STREAK_MIN_STEPS:
        j -= 1
    return i - j  # j == -1 -> never active -> i + 1


# ─────────────────────────────────────────────────────────────────────────────
# Feature construction
# ─────────────────────────────────────────────────────────────────────────────


def _build_user_features(user_id: str, user_rows: list[dict]) -> list[dict]:
    """Build one user's ML-ready rows from their day-sorted raw rows."""
    steps = [r["steps"] for r in user_rows]
    minutes = [r["active_minutes"] for r in user_rows]
    captured = [r["hexes_captured"] for r in user_rows]
    lost = [r["hexes_lost"] for r in user_rows]
    owned = [r["hexes_owned"] for r in user_rows]
    defense = [r["defense_steps"] for r in user_rows]
    goals_done = [r["goal_completed"] for r in user_rows]

    out: list[dict] = []
    for i, row in enumerate(user_rows):
        w7_steps = _window(steps, i, 7)
        w7_steps_sum = sum(w7_steps)
        prior7 = steps[max(0, i - 7) : i]  # previous 7 days, excluding D

        out.append(
            {
                # metadata (never features)
                "synthetic_user_id": user_id,
                "day": row["day"],
                # activity
                "steps_today": steps[i],
                "active_minutes_today": minutes[i],
                "steps_3d_avg": _f6(_mean(_window(steps, i, 3))),
                "steps_7d_avg": _f6(_mean(w7_steps)),
                "active_minutes_3d_avg": _f6(_mean(_window(minutes, i, 3))),
                "active_minutes_7d_avg": _f6(_mean(_window(minutes, i, 7))),
                "activity_days_7d": sum(
                    1 for s in w7_steps if s >= STREAK_MIN_STEPS
                ),
                "steps_change_vs_7d_avg": (
                    _f6(steps[i] - _mean(prior7)) if prior7 else 0.0
                ),
                # consistency
                "current_streak": row["streak"],
                "goal_completion_rate_7d": _f6(_mean(_window(goals_done, i, 7))),
                "days_since_active": _days_since_active(steps, i),
                # territory (as of end of day D)
                "hexes_owned": owned[i],
                "captures_7d": sum(_window(captured, i, 7)),
                "losses_7d": sum(_window(lost, i, 7)),
                "territory_change_7d": owned[i] - (owned[i - 7] if i >= 7 else 0),
                "defense_steps_7d": sum(_window(defense, i, 7)),
                "defense_ratio_7d": (
                    _f6(sum(_window(defense, i, 7)) / w7_steps_sum)
                    if w7_steps_sum
                    else 0.0
                ),
                # goals
                "goal_steps": row["goal_steps"],
                "goal_completed_today": goals_done[i],
                # derived extras
                "active_today": 1 if steps[i] >= STREAK_MIN_STEPS else 0,
                "goal_progress_ratio": (
                    _f6(steps[i] / row["goal_steps"]) if row["goal_steps"] else 0.0
                ),
                # provenance (never a feature)
                "data_source": row.get("data_source", DATA_SOURCE),
            }
        )
    return out


def build_features(raw_rows: list[dict]) -> list[dict]:
    """Transform raw daily rows (generator output or reread CSV) into
    ML-ready feature rows — one per (user, day), in input user order with
    each user's days ascending.

    Pure function: no I/O, stdlib only, deterministic for identical input.
    """
    if not raw_rows:
        raise ValueError("cannot build features from an empty dataset")

    rows = [_normalize_row(r) for r in raw_rows]
    grouped: dict[str, list[dict]] = {}
    for row in rows:
        grouped.setdefault(row["synthetic_user_id"], []).append(row)

    out: list[dict] = []
    for user_id, user_rows in grouped.items():
        user_rows.sort(key=lambda r: r["day"])  # defensive; input is ordered
        out.extend(_build_user_features(user_id, user_rows))
    return out


# ─────────────────────────────────────────────────────────────────────────────
# I/O
# ─────────────────────────────────────────────────────────────────────────────


def write_features(rows: list[dict], output_path: str | Path) -> Path:
    """Write feature rows to CSV in canonical column order. Returns the path."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)
    return path


def read_features(input_path: str | Path) -> list[dict]:
    """Read a feature CSV back into row dicts (values as strings)."""
    path = Path(input_path)
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_manifest(output_path: str | Path, source_path: str | Path | None = None) -> Path:
    """Write the machine-readable feature manifest (JSON) for reproducibility."""
    doc = {
        "dataset": (
            "FitQuest synthetic fitness ML-ready features — SYNTHETIC data, "
            "not real user data; demonstrates pipeline feasibility only and "
            "establishes no real-world predictive performance."
        ),
        "generated_from": str(source_path) if source_path else None,
        "n_model_features": len(MODEL_FEATURES),
        "model_features": MODEL_FEATURES,
        "metadata_columns": METADATA_COLUMNS + ["data_source"],
        "leakage_policy": (
            "Every feature is computed only from the sample's own day D and "
            "earlier days of the SAME user; trailing windows are inclusive of "
            "D and expand at history start; no future rows and no cross-user "
            "data contribute to any feature."
        ),
        "target": (
            "None by design — Phase 4B.3 decides the learning target; the "
            "rules engine's recommendation labels are deliberately NOT used "
            "as ground truth."
        ),
        "features": FEATURE_MANIFEST,
    }
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(doc, handle, indent=2)
        handle.write("\n")
    return path


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="synthetic_features",
        description=(
            "Build ML-ready features from the SYNTHETIC fitness dataset "
            "(never present them as real user data)."
        ),
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="raw daily dataset CSV (generator output)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="ML-ready feature CSV path",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="machine-readable feature manifest JSON path",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_arg_parser().parse_args(argv)

    raw_rows = generator.read_dataset(args.input)
    features = build_features(raw_rows)
    out_path = write_features(features, args.output)
    manifest_path = write_manifest(args.manifest, source_path=args.input)

    n_users = len({row["synthetic_user_id"] for row in features})
    print(f"Read {len(raw_rows)} raw rows from {args.input}")
    print(
        f"Wrote {len(features)} ML-ready rows ({n_users} users, "
        f"{len(MODEL_FEATURES)} model features) to {out_path}"
    )
    print(f"Wrote feature manifest to {manifest_path}")
    print(f"rows are data_source={DATA_SOURCE!r} | no ML target defined (Phase 4B.3)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
